repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
        files: '.(c|h|hpp|cpp)$'
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
      additional_dependencies: [pyyaml>=5.1]
    - id: cmake-lint
      additional_dependencies: [pyyaml>=5.1]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
